Reduce ambiguous paths in macros (#458)
Current macros are not hygienic in path resolution. This causes compile
error with codes like below.

```rust
deno_core::extension!(
    ext,
    js = [ "/path/to/ext.js" ]
);

mod std {}
```

error diagnostic:

```
error[E0433]: failed to resolve: could not find `borrow` in `std`
  --> src/lib.rs:14:1
   |
14 | / deno_core::extension!(
15 | |     ext,
16 | |     js = [ "/path/to/ext.js" ],
17 | | );
   | |_^ could not find `borrow` in `std`
   |
   = note: this error originates in the macro `deno_core::extension` (in Nightly builds, run with -Z macro-backtrace for more info)
```

This PR almost resolves this problem, by using unambiguous paths. There
are still ambiguous paths remaining, but they won't couse such a issue
because they only appear in unexported macros. I'm sorry if I missed
something :pray:

references about hygienic macro:

- https://en.wikipedia.org/wiki/Hygienic_macro
- https://doc.rust-lang.org/reference/macros-by-example.html#hygiene
- https://gist.github.com/Kestrer/8c05ebd4e0e9347eb05f265dfb7252e1